import Head from 'next/head'
import Button from 'components/Button'
import { useEffect } from 'react'
import { SiGithub } from 'react-icons/si'
import { githubPovider } from 'firebase/cliente'
import { useRouter } from 'next/router'
import useUser, { USER_STATE } from 'hooks/useUser'

const Home = () => {
   const user = useUser()
   const { replace } = useRouter()

   useEffect(() => {
      user && replace('/home')
   }, [user])

   const loginGithub = () => {
      githubPovider().catch(err => console.log(err))
   }

   return (
      <div>
         <Head>
            <title>🥩Create Next App ™</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <section>
            <h1>Devtter</h1>
            <article>
               <h1>tweet xd</h1>
            </article>
            {user === USER_STATE.NOT_LOGGED && (
               <Button onClick={loginGithub}>
                  <SiGithub />
                  Sign Up with Github
               </Button>
            )}
            {user === USER_STATE.NOT_KNOW && <span>Loading...</span>}
         </section>
         <style jsx>{`
            section {
               width: 500px;
               height: 600px;
               margin: 50px auto;
               display: flex;
               flex-direction: column;
               text-align: center;
            }
         `}</style>
      </div>
   )
}

export default Home
