import NotLoggedUser from 'components/NotLoggedUser'
import { getSession } from 'next-auth/react'
import Head from 'next/head'

const Index = () => {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <NotLoggedUser />
      </>
   )
}

export async function getServerSideProps(context) {
   const session = await getSession(context)
   if (!session) {
      return {
         props: {}
      }
   }
   return {
      redirect: {
         destination: '/home',
         permanent: false
      }
   }
}

export default Index
